### ISSUE TITLE
Difficulty handling components unique to environments

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#292]
Configuration files seem to commonly fall into one or more of these patterns:

1. Configurations that are identical across environments (_i.e._, same in
   _prod_, _dev_, and _staging_).
2. Configurations that are nearly identical, however have simple parameters
   that need to be tweaked across environments (_i.e._, _prod_ accessing a
   different _mysql_ server than _dev_) 
3. Configurations that are similar, however, have chunks of code that are
   entirely different between environments
4. Configurations that are distinctively used in a single environment.

ksonnet does a decent job supporting the first two, however, we currently don't
support 3 and 4 easily, without manipulating the configuration files substantially.

========

Based on the proposals of #295, we'll need to implement:

- [x] *#315* Common metadata handling
- [x] *#309, #308* `app.yaml` to handle environment spec, remove `spec.json`.
- [x] *#319* Add concept of targets and component hierarchy.
- [x] *#319* Update handling of params.libsonnet to include component namespaces
- [x] *WON'T DO, `diff` becomes ambiguous on which clusters to diff.* 
  - *#324* Better multi-cluster deployment support to `ks`
  - Add concept of destinations, update commands accordingly.
  - Introduce `env.yaml` for overriding.
- [x] *#327* Add migration for users using < 0.9.0 environments

**Comment by jessicayuen** [comment]
I'm going to work on a proposal for this, but please feel free to share thoughts @hausdorff @bryanl .

**Comment by jessicayuen** [comment]
Based on the proposals of #295, we'll need to implement:

- [ ] Common metadata handling
- [ ] `app.yaml` to handle environment spec, remove `spec.json`.
- [ ] Add concept of targets and component hierarchy.
- [ ] Update handling of params.libsonnet to include component namespaces
- [ ] Add concept of destinations, update commands accordingly.
- [ ] Introduce `env.yaml` for overriding.

**Comment by abiogenesis-now** [comment]
@jessicayuen what are your thoughts on having either `includes` or `excludes` rather than `targets` (which is basically an `includes`)?

As it is, it's possible to work around this by using a "shared" component subdirectory. However, there's usually some sort of tipping point where either `includes` or `excludes` become easier to write, and having both would let users choose what's right for them.

(I've seen this sort of syntax in Ark backups).

**Comment by jessicayuen** [comment]
@abiogenesis-now Interesting idea, what is the default where an environment doesn't have `includes` or `excludes` specified?

**Comment by abiogenesis-now** [comment]
Hm, in that case, I think it makes sense to include all of the components (since that's usually what you want for a simple app).

**Comment by abiogenesis-now** [comment]
Followup based on discussion: There's enough flexibility provided by the "component namespaces" (what you get from the directory structure) that `targets` should be sufficient

**Comment by marccarre** [comment]
Until this issue gets resolved, how would one [exclude](https://github.com/ksonnet/ksonnet/issues/292#issuecomment-362016331) a _Component_ from a specific _Environment_?
So far, I have this under `environments/<env-to-exclude-from>/main.jsonnet`:
```jsonnet
local origBase = import "../base.libsonnet";
local base = { [k]: origBase[k] for k in std.filter(
  function(k) k != '<name-of-the-component-to-exclude>', std.objectFields(origBase)
) };
```
which _seems_ to work on a toy project.
However, being new to both `ksonnet` and `jsonnet`, a confirmation from experts would be better :slightly_smiling_face:.

N.B.: 
- this scenario is a specific instance of [category 4. above](https://github.com/ksonnet/ksonnet/issues/292#issue-290104127) ;
- this is a very common scenario, as even when simply rolling a new _Component_ forward from `dev` to `prod`, one may not want to deploy this _Component_ to `prod` just yet.

*[Apologies in advance if you think this should be a separate issue, or should be asked elsewhere]*

**Comment by redbaron** [comment]
@marccarre: just set it to empty, it should render no items then:

```
local base = import "../base.libsonnet";
base + { "<name-of-the-component-to-exclude": null }
```

**Comment by Quentin-M** [comment]
Hey there,

Just starting with ksonnet and I have been trying to wrap my mind around the general design of an application with that change.

Specifically, we'd like to create an app that would contain the definition of our infrastructure as a whole, with multiple regions/clusters/namespaces, and with applications that are present on several regions/clusters/namespaces and some other applications used only in one environment.

What I have so far looks like the following:

### tree
```
components/
| - params.libsonnet
| - <region>/
|  | - <cluster>/
|  |  | - <namespace 1>/
|  |  |  | - graphite.jsonnet
|  |  |  | - other-app.jsonnet
|  |  |  | - params.libsonnet
|  |  | - <namespace 2>/
|  |  |  | - graphite.jsonnet
|  |  |  | - params.libsonnet

environments/
| - base.libsonnet
| - <region>/
|  | - <cluster>/
|  |  | - <namespace 1>/
|  |  |  | - main.jsonnet
|  |  |  | - params.libsonnet
```

### app.yaml
```
apiVersion: 0.0.1
version: 0.0.1
kind: ksonnet.io/app
name: k8s-manifests

environments:
  <region>/<cluster>/<namespace>:
    k8sVersion: v1.9.0
    path: <region>/<cluster>/<namespace>
    destination:
      server: <server>
      namespace: <namespace>
    targets:
      - <region>/<cluster>/<namespace>
```

Where `graphite.jsonnet` would be nothing more but importing/parametrizing/extending a prototype for the graphite application (which include relay/cache/redis).

This is great for discovery purposes as it is very easy to understand what is being deployed where at a glance. However, I feel like this renders `environments/` pretty much useless as all targets
 components and their parameters are now already namespaced/defined in `components/`.

However, if I flatten `components/` to become namespaced/organized by application, and leverage `app.yaml` more to define what application should be deployed, and the `environments` for parametrization, I feel like the use for prototypes becomes less relevant?

### tree
```
components/
| - params.libsonnet
| - graphite/
| | - relay.jsonnet
| | - cache.jsonnet
| | - redis.jsonnet
| | - params.libsonnet
| - other-app.jsonnet
| - params.libsonnet

environments/
| - base.libsonnet
| - <region>/
|  | - <cluster>/
|  |  | - <namespace 1>/
|  |  |  | - main.jsonnet
|  |  |  | - params.libsonnet
```

### app.yaml
```
apiVersion: 0.0.1
version: 0.0.1
kind: ksonnet.io/app
name: k8s-manifests

environments:
  <region>/<cluster>/<namespace>:
    k8sVersion: v1.9.0
    path: <region>/<cluster>/<namespace>
    destination:
      server: <server>
      namespace: <namespace>
    targets:
      - graphite/
      - other-app.jsonnet
```

Writing this, I feel like the second solution is saner, and thus would indeed be closer to ksonnet's design. I also imagine that redis and graphite would be their own parts/prototypes - combined in one component, with added parameters to link the two together.

Thanks.
