### ISSUE TITLE
Iteration plan for 0.9

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#306]
## Plan Items

In preparation for [ksonnet 1.0](https://github.com/ksonnet/ksonnet/blob/master/design/roadmap.md), during the 0.9 sprint, we are focusing on components and ksonnet-lib generation. 

#### Features

- [x] Component hierarchies #292 **@jessicayuen**
- [x] Remove components by name #243 **@jessicayuen**
- [x] Access namespace in components #222 **@jessicayuen**
- [x] List components #242 **@jessicayuen**

#### Bugs

- [x] Remove build template from client-go version #250 **@bryanl**
- [x] Packages with same names from different registries conflict #269 **@jessicayuen**
- [x] Version parsing causes errors #236 

### ksonnet-lib

- [x] Generate k8s.libsonnet using Jsonnet Go AST #221 **@bryanl**
- [x] ksonnet lib custom constructors  #304 **@bryanl**

---

### Upcoming projects

* ksonnet registry server #305 **@bryanl**
