### ISSUE TITLE
Implement environment params

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#31]
- [x] **PR #40** Generate `components/params.libsonnet` file on `ks init`
- [x] **PR #40** Generate `environments/<env>/params.libsonnet` file on `env add ...`
- [x] **PR #40** Expand the environment `params.libsonnet` file and make accessible as `extVar`.
- [x] **PR #40** Components generated from `ks prototype use ... ` need to populate `components/params.libsonnet`
- [x] **PR #40** Components generated from `ks prototype use ... ` need to reference the params from the component file.
- Operations needed (around manipulating jsonnet) to support the below commands:
   - [x]  **PR #40** Write component parameters
   - [x] **PR #40** Read component parameters
   - [x] **PR #40** Write environment parameters
   - [x] **PR #40** Read environment parameters
- Commands: 
   - [x] **PR #40** `ks param diff <env> <env> [--component]`
   - [x] **PR #40** `ks param set <component> <param> <value> [--env]`
   - [x] **PR #40** `ks param list <component> [--env]`

**Comment by jessicayuen** [comment]
Closing this. Opened issues #61, #45 for related future work.
