### ISSUE TITLE
Iteration plan for release 0.10

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#360]
- [x] Easier libraries. Should be able to host a part as a local directory #232
- [x] Use yaml, json, plain jsonnet, and ksonnet as components #240
- [x] Ksonnet lib update mechanism #454 
- [x] Env overrides #370 
- [x] Better integration tests for the site using newer use cases

Ongoing code cleanups to make ksonnet easier to work with:
* Continue deprecating manager where possible
* Move kubecfg items to actions
* Investigate using viper instead of flags directly
