### ISSUE TITLE
ksonnet 0.11 sprint

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#528]
ksonnet development will continue to mature existing features and implement new required functionality:

# Themes

- [x] 0.11 Documentation 
- [x] Diff #529 
- [x] Apply with patching #200
- [x] Don't use ksonnet-lib in built in prototypes #548
- [x] Support components returning lists of objects #540
