### ISSUE TITLE
Update/refresh registries and packages - Parent Issue

### ISSUE THREAD

**Issue by shomron** [ksonnet/ksonnet#629]
Consolidating related issues here:

- [ ] Expose environment and version information in pkg list #626
- [ ] Package cache garbage collection #624
- [ ] Add pkg remove command #625

**Comment by bryanl** [comment]
@shomron where does `ks upgrade can update vendored packages to their proper location to silence the upgrade warning` fit?

**Comment by shomron** [comment]
@bryanl I'm now tracking that in #663. Here is an early, incomplete sketch:

https://github.com/shomron/ksonnet/tree/upgrade-0.2.0

**Comment by bryanl** [comment]
@shomron What will be the command for upgrading to latest?

**Comment by shomron** [comment]
@bryanl the following sequence demonstrates how you can currently upgrade a package

```
$ ksdev init pkg-upgrade && cd pkg-upgrade/
$ ksdev env add stage
$ ksdev pkg install --env=stage incubator/nginx@consistency    # some old version
$ ksdev pkg install --env=stage incubator/nginx    # latest according to registry uri
```

We start running into problems with the current cli when you want multiple environments to point to the same package version - it currently reports that as a conflict (package already exists).

I can do a writeup on how we might overcome this.
